language: python

python:
        -  2.7
env:
    - DEV
install:
        - pip install -r requirements.txt
        - pip install codecov
        - pip install pylint

script:
        - coverage erase
        - pytest
        - pylint --output-format=text --disable=wrong-import-position,unused-argument app


after_success:
        - codecov --token=$codecov_token
