language: python

python:
        -  2.7
        -  3.6

env:
        - FLASK_APP=app
        - FLASK_ENV=development

install:
        - pip install -r requirements.txt
        - pip install codecov
        - pip install pylint

script:
        - coverage erase
        - coverage run --source=app -m app.tests.test_questions && coverage html
        - pylint --output-format=text --disable=wrong-import-position,unused-argument app
     

after_success:
        - codecov --token=e491af6c-4d42-41d6-a693-7c96f4dd5d67

