language: python

python:
        -  2.7
install:
        - pip install -r requirements.txt
        - pip install codecov
        - pip install pylint

script:
        - coverage erase
        - pytest


after_success:
        - codecov --token=$codecov_token
