language: python

python:
        -  2.7
        -  3.6
        -  3.5

install:
        - pip install -r requirements.txt
        - pip install codecov
        - pip install pylint

script:
        - coverage erase
        - coverage run --source=app -m app.tests.test_questions && coverage html
     

after_success:
        - codecov


script:
        - pylint --output-format=text app
