language: python

python:
        -  2.7

install:
        - pip install -r requirements.txt
        - pip install codecov
        - pip install pylint

script:
        - coverage erase
        - coverage run --source=app -m app.tests.test_questions && coverage html
        - pylint --output-format=text --disable=wrong-import-position,unused-argument app
     

after_success:
        - codecov --token=$codecov_token

deploy:
  provider: heroku
  api_key: $api_key
  app: kaburu-stackoverflow-lite
