language: python

python:
        -  2.7
install:
        - pip install -r requirements.txt
        - pip install codecov
        - pip install pylint

script:
        - coverage erase
        - pytest --cov app


after_success:
        - codecov 
